spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/locadora
    username: postgres
    password: Ravi@2008
    driver-class-name: org.postgresql.Driver

jpa:
  hibernate:
    ddl-auto: validate
  show-sql: true
  properties:
    hibernate:
      format_sql: true
  database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080